### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by kappa95** [jhavl/swift#50]
Dear community,

I tried to do the base tutorial for showing the Panda robot. But I get a black screen on the browser with the error: "Application error: a client-side exception has occurred (see the browser console for more information)."

On the browser console i get the following errors:

`Error: Could not load retrieve/C:\Users\inse9\AppData\Local\Programs\Python\Python38\Lib\site-packages\rtbdata\xacro\franka_description\meshes\visual\link0.dae: fetch for "http://localhost:52000/retrieve/C:/Users/inse9/AppData/Local/Programs/Python/Python38/Lib/site-packages/rtbdata/xacro/franka_description/meshes/visual/link0.dae" responded with 404: File not found)
    NextJS 2
[index-0723cc3b940b78c7.js:194:40195](http://localhost:52000/_next/static/chunks/pages/index-0723cc3b940b78c7.js)
Error: Could not load retrieve/C:\Users\inse9\AppData\Local\Programs\Python\Python38\Lib\site-packages\rtbdata\xacro\franka_description\meshes\visual\link1.dae: fetch for "http://localhost:52000/retrieve/C:/Users/inse9/AppData/Local/Programs/Python/Python38/Lib/site-packages/rtbdata/xacro/franka_description/meshes/visual/link1.dae" responded with 404: File not found)
    NextJS 2
[index-0723cc3b940b78c7.js:194:40195](http://localhost:52000/_next/static/chunks/pages/index-0723cc3b940b78c7.js)
Error: Could not load retrieve/C:\Users\inse9\AppData\Local\Programs\Python\Python38\Lib\site-packages\rtbdata\xacro\franka_description\meshes\visual\link2.dae: fetch for "http://localhost:52000/retrieve/C:/Users/inse9/AppData/Local/Programs/Python/Python38/Lib/site-packages/rtbdata/xacro/franka_description/meshes/visual/link2.dae" responded with 404: File not found)
    NextJS 2
[index-0723cc3b940b78c7.js:194:40195](http://localhost:52000/_next/static/chunks/pages/index-0723cc3b940b78c7.js)
Error: Could not load retrieve/C:\Users\inse9\AppData\Local\Programs\Python\Python38\Lib\site-packages\rtbdata\xacro\franka_description\meshes\visual\link3.dae: fetch for "http://localhost:52000/retrieve/C:/Users/inse9/AppData/Local/Programs/Python/Python38/Lib/site-packages/rtbdata/xacro/franka_description/meshes/visual/link3.dae" responded with 404: File not found)
    NextJS 2
[index-0723cc3b940b78c7.js:194:40195](http://localhost:52000/_next/static/chunks/pages/index-0723cc3b940b78c7.js)
Error: Could not load retrieve/C:\Users\inse9\AppData\Local\Programs\Python\Python38\Lib\site-packages\rtbdata\xacro\franka_description\meshes\visual\link4.dae: fetch for "http://localhost:52000/retrieve/C:/Users/inse9/AppData/Local/Programs/Python/Python38/Lib/site-packages/rtbdata/xacro/franka_description/meshes/visual/link4.dae" responded with 404: File not found)
    NextJS 2
[index-0723cc3b940b78c7.js:194:40195](http://localhost:52000/_next/static/chunks/pages/index-0723cc3b940b78c7.js)
Error: Could not load retrieve/C:\Users\inse9\AppData\Local\Programs\Python\Python38\Lib\site-packages\rtbdata\xacro\franka_description\meshes\visual\link5.dae: fetch for "http://localhost:52000/retrieve/C:/Users/inse9/AppData/Local/Programs/Python/Python38/Lib/site-packages/rtbdata/xacro/franka_description/meshes/visual/link5.dae" responded with 404: File not found)
    NextJS 2
[index-0723cc3b940b78c7.js:194:40195](http://localhost:52000/_next/static/chunks/pages/index-0723cc3b940b78c7.js)
Error: Could not load retrieve/C:\Users\inse9\AppData\Local\Programs\Python\Python38\Lib\site-packages\rtbdata\xacro\franka_description\meshes\visual\link6.dae: fetch for "http://localhost:52000/retrieve/C:/Users/inse9/AppData/Local/Programs/Python/Python38/Lib/site-packages/rtbdata/xacro/franka_description/meshes/visual/link6.dae" responded with 404: File not found)
    NextJS 2
[index-0723cc3b940b78c7.js:194:40195](http://localhost:52000/_next/static/chunks/pages/index-0723cc3b940b78c7.js)
Error: Could not load retrieve/C:\Users\inse9\AppData\Local\Programs\Python\Python38\Lib\site-packages\rtbdata\xacro\franka_description\meshes\visual\link7.dae: fetch for "http://localhost:52000/retrieve/C:/Users/inse9/AppData/Local/Programs/Python/Python38/Lib/site-packages/rtbdata/xacro/franka_description/meshes/visual/link7.dae" responded with 404: File not found)
    NextJS 2
[index-0723cc3b940b78c7.js:194:40195](http://localhost:52000/_next/static/chunks/pages/index-0723cc3b940b78c7.js)
Error: Could not load retrieve/C:\Users\inse9\AppData\Local\Programs\Python\Python38\Lib\site-packages\rtbdata\xacro\franka_description\meshes\visual\hand.dae: fetch for "http://localhost:52000/retrieve/C:/Users/inse9/AppData/Local/Programs/Python/Python38/Lib/site-packages/rtbdata/xacro/franka_description/meshes/visual/hand.dae" responded with 404: File not found)
    NextJS 2
[index-0723cc3b940b78c7.js:194:40195](http://localhost:52000/_next/static/chunks/pages/index-0723cc3b940b78c7.js)
Error: Could not load retrieve/C:\Users\inse9\AppData\Local\Programs\Python\Python38\Lib\site-packages\rtbdata\xacro\franka_description\meshes\visual\finger.dae: fetch for "http://localhost:52000/retrieve/C:/Users/inse9/AppData/Local/Programs/Python/Python38/Lib/site-packages/rtbdata/xacro/franka_description/meshes/visual/finger.dae" responded with 404: File not found)
    NextJS 2
[index-0723cc3b940b78c7.js:194:40195](http://localhost:52000/_next/static/chunks/pages/index-0723cc3b940b78c7.js)
Error: Could not load retrieve/C:\Users\inse9\AppData\Local\Programs\Python\Python38\Lib\site-packages\rtbdata\xacro\franka_description\meshes\visual\finger.dae: fetch for "http://localhost:52000/retrieve/C:/Users/inse9/AppData/Local/Programs/Python/Python38/Lib/site-packages/rtbdata/xacro/franka_description/meshes/visual/finger.dae" responded with 404: File not found)
    NextJS 2
[index-0723cc3b940b78c7.js:194:40195](http://localhost:52000/_next/static/chunks/pages/index-0723cc3b940b78c7.js)
Error: Could not load retrieve/C:\Users\inse9\AppData\Local\Programs\Python\Python38\Lib\site-packages\rtbdata\xacro\franka_description\meshes\visual\finger.dae: fetch for "http://localhost:52000/retrieve/C:/Users/inse9/AppData/Local/Programs/Python/Python38/Lib/site-packages/rtbdata/xacro/franka_description/meshes/visual/finger.dae" responded with 404: File not found)
    NextJS 2
[framework-37f5df078e1d84d6.js:9:69814](http://localhost:52000/_next/static/chunks/framework-37f5df078e1d84d6.js)
Error: Could not load retrieve/C:\Users\inse9\AppData\Local\Programs\Python\Python38\Lib\site-packages\rtbdata\xacro\franka_description\meshes\visual\finger.dae: fetch for "http://localhost:52000/retrieve/C:/Users/inse9/AppData/Local/Programs/Python/Python38/Lib/site-packages/rtbdata/xacro/franka_description/meshes/visual/finger.dae" responded with 404: File not found)`

I have tried with Python 3.8 and 3.9 and with the browsers: Firefox and Chrome on Windows 11. But same error appears.

How can I solve?

**Comment by oldgunlu** [comment]
Same Problem here

**Comment by oldgunlu** [comment]
Error in Terminal is 


connection handler failed
Traceback (most recent call last):
  File "C:\Users\n.Lu\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 959, in transfer_data
    message = await self.read_message()
  File "C:\Users\n.Lu\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 1029, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "C:\Users\n.Lu\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 1104, in read_data_frame
    frame = await self.read_frame(max_size)
  File "C:\Users\n.Lu\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 1165, in read_frame
    extensions=self.extensions,
  File "C:\Users\n.Lu\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\framing.py", line 68, in read
    data = await reader(2)
  File "C:\Users\n.Lu\AppData\Local\Programs\Python\Python37\lib\asyncio\streams.py", line 679, in readexactly
    await self._wait_for_data('readexactly')
  File "C:\Users\n.Lu\AppData\Local\Programs\Python\Python37\lib\asyncio\streams.py", line 473, in _wait_for_data
    await self._waiter
  File "C:\Users\n.Lu\AppData\Local\Programs\Python\Python37\lib\asyncio\selector_events.py", line 801, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\n.Lu\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\server.py", line 240, in handler
    await self.ws_handler(self)
  File "C:\Users\n.Lu\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\server.py", line 1189, in _ws_handler
    )(websocket, websocket.path)
  File "C:\Users\n.Lu\AppData\Local\Programs\Python\Python37\lib\site-packages\swift\SwiftRoute.py", line 320, in serve
    await self.expect_message(websocket, expected)
  File "C:\Users\n.Lu\AppData\Local\Programs\Python\Python37\lib\site-packages\swift\SwiftRoute.py", line 325, in expect_message
    recieved = await websocket.recv()
  File "C:\Users\n.Lu\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 568, in recv
    await self.ensure_open()
  File "C:\Users\n.Lu\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent

**Comment by oldgunlu** [comment]
I think it related to the issue of Swift, similar with:
https://github.com/jhavl/swift/issues/4

but I tried to using 
from roboticstoolbox.backends.swift import Swift
and also tried to add
os.chdir(root_dir.anchor)  in SwiftRoute.py and even switch back to Python 3.6

but unfortunately nothing works.
Hopefully it will be fixed soon.

**Comment by jonarriza96** [comment]
Same here when trying to record a video. Without recording it works great. Browser: Firefox, OS: Ubuntu 20

**Comment by ningmimg** [comment]
@oldgunlu I have the same problem. Have you found any other viable alternatives?

**Comment by kappa95** [comment]
The pull request #52 solved the issue for me. Temporary solution: make that changes on your path.

**Comment by oldgunlu** [comment]
@kappa95 Problem solved, Thanks a lot !
@ningtianze you can try to make change, it works for me in windows： https://github.com/jhavl/swift/pull/52

**Comment by kongyuanchao** [comment]
same issues happened on Windows

**Comment by kanyunke** [comment]
On windows, same problem, pull request #52 solved for me too.

**Comment by chaoyuefei** [comment]
> Same here when trying to record a video. Without recording it works great. Browser: Firefox, OS: Ubuntu 20

@jonarriza96 Same for me. Browser: Brave, OS: Mac M3 Sequoia and the browser's console shows:
`Error: Incorrect or missing format: Valid formats are gif, webm, ffmpegserver, png, jpg, webm-mediarecorder`

Have you found a way to fix it?

**Comment by juliabeliaeva** [comment]
> > Same here when trying to record a video. Without recording it works great. Browser: Firefox, OS: Ubuntu 20
> 
> [@jonarriza96](https://github.com/jonarriza96) Same for me. Browser: Brave, OS: Mac M3 Sequoia and the browser's console shows: `Error: Incorrect or missing format: Valid formats are gif, webm, ffmpegserver, png, jpg, webm-mediarecorder`
> 
> Have you found a way to fix it?

I have a similar issue on a mac in chrome. Have you found a solution?
