### ISSUE TITLE
"RuntimeError: no running event loop" cannot run any example code

### ISSUE THREAD

**Issue by Celppu** [jhavl/swift#57]
Trying any example codes that uses swift.

Installed via pip with roboticstoolbox
So far I have tested python versions 3.10 and 3.13
On windows and linux.

error:
`Exception in thread Thread-3 (SwiftSocket):
Traceback (most recent call last):
  File "c:\Users\mee\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "c:\Users\mee\AppData\Local\Programs\Python\Python312\Lib\site-packages\ipykernel\ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
  File "c:\Users\mee\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\mee\AppData\Local\Programs\Python\Python312\Lib\site-packages\swift\SwiftRoute.py", line 296, in __init__
    start_server = websockets.serve(self.serve, "localhost", port)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\mee\AppData\Local\Programs\Python\Python312\Lib\site-packages\websockets\asyncio\server.py", line 737, in __init__
    self.server = Server(
                  ^^^^^^^
  File "c:\Users\mee\AppData\Local\Programs\Python\Python312\Lib\site-packages\websockets\asyncio\server.py", line 281, in __init__
    self.loop = asyncio.get_running_loop()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop`

**Comment by renehorstmann** [comment]
Added a pull request that fixes this bug

#58

**Comment by AliRezaBeigy** [comment]
@jhavl could you take look at @renehorstmann pull request, we face same issue

**Comment by rovalder** [comment]
Fast fix 

```bash
pip uninstall websockets
pip install websockets==13.1
```

**Comment by dewgonlong** [comment]
Hi,I had solve that issue ,by this method:
my code:
_import roboticstoolbox as rtb

model = rtb.models.URDF.UR10()
print(model)
qz = [0,30,-30,0,0,0]
model.plot(qz,backend = 'swift')_

fast  fix
_pip uninstall websockets
pip install websockets==13.1_

but the pycharm open with the google,with the error:
_Application error: a client-side exception has occurred (see the browser console for more information)._

**Comment by dewgonlong** [comment]
> Fast fix
> 
> pip uninstall websockets
> pip install websockets==13.1

Hi,I had solve that issue ,by this method:
but the pycharm open  the google,with the error:
Application error: a client-side exception has occurred (see the browser console for more information).
the  browser console show that :
 cannot open :http://localhost:52000/retrieve/D:/Program%20Files%20(x86)/Python311/Lib/site-packages/rtbdata/xacro/ur_description/meshes/ur10/visual/upperarm.dae 

Error response
Error code: 404
Message: File not found.
Error code explanation: 404 - Nothing matches the given URI.
